# Generated by Django 4.0.2 on 2022-03-12 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recurring',
            fields=[
                ('recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='liability',
            fields=[
                ('liability_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='daily',
            fields=[
                ('dayId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grocExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gasExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uberExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alcExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('barberExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('barExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stockExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cryptoExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('debtExp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('appreciation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('acquisition_date', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
