# Generated by Django 4.0.2 on 2022-03-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_asset_appreciation_liability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='appreciation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='liability',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='liability',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='liability',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
