# Generated by Django 4.0.2 on 2022-03-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring',
            old_name='cost',
            new_name='value',
        ),
    ]
