# Generated by Django 4.0.2 on 2022-03-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_asset_appreciation_alter_asset_depreciation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='duration',
        ),
    ]
